### PR TITLE
ReadToEnd future cleanup

### PR DESCRIPTION
**Pull request by Ralith**
You can't do anything with a finished receive stream, so there's no point preserving it even under futures 0.1 idioms.

### CODE REVIEW

**Comment by Ralith** [comment]
Tweaked the optimization to be less dubious. This was motivated by [a flamegraph](https://i.imgur.com/rTECAka.png) @nbaksalyar posted which showed the reallocs taking a huge chunk of time in many_connections, though it's been difficult to show an absolute time improvement, perhaps due to confounding factors in that particular test. Still, this seems like the same thing that bit us in the original `VecDeque<u8>` `Assembler` impl.

**Comment by djc** [comment]
To be sure this version makes sense. I just think we should have a really good case for using unsafe blocks.

**Comment by djc** [comment]
BTW, this still seems to create a return value that potentially starts with a lot of zero bytes. Is that really what we want? If so, we should at least document the behavior IMO.

**Comment by Ralith** [comment]
> BTW, this still seems to create a return value that potentially starts with a lot of zero bytes

I don't think this is true. We only return a buffer if we receive `ReadError::Finished`, which guarantees that every byte of the stream has been read.

**Comment by djc** [comment]
But what if some parts of the stream had been read using ordered reads before starting unordered reads?

**Comment by Ralith** [comment]
Good catch; documented the case. Alternatively, we could set a flag on any read and panic or return an error if the flag's set on the `read_to_end` call.

**Comment by djc** [comment]
Yeah, I think I'd prefer to set a flag such that `read_to_end()` will return an `Err` if any other read has been done on the stream. In my opinion the current design is a little hard to explain, and only allowing `read_to_end()` from offset 0 doesn't seem a very onerous restriction.

**Comment by Ralith** [comment]
How's this?

**Comment by djc** [comment]
Great!

**Pull request merged**
