### PR TITLE
Fixed Clippy Warnings

### PR DESCRIPTION
**Pull request by TimonPost**

### CODE REVIEW

**Comment by TimonPost** [comment]
There are some left, but those are difficult to resolve.  Those are about complex functions.

**Comment by TimonPost** [comment]
No problem, I will do a merge.

**Comment by TimonPost** [comment]
I don't know why the CI failed. It looks like a false report.

**Comment by Ralith** [comment]
The CI issue was probably the one fixed by #534; rebasing should sort it out.

**Comment by djc** [comment]
I think we'll want to land #489 first.

**Comment by djc** [comment]
If you rebase this again, I'm happy to land it!

**Comment by djc** [comment]
Felt bad about asking you to rebase this again, so I did it for you:

https://github.com/djc/quinn/compare/timon/clippy

If you pull this into your branch, we can merge it.

**Pull request merged**
