### PR TITLE
Fix hang in ReadExact future

### PR DESCRIPTION
**Pull request by Ralith**
A successful read of less than the desired buffer size would result in `Poll::Pending` being returned without a waker having been registered.

This is a fairly typical hand-implemented future bug; mark down another point in favor of switching to anonymous, `!Unpin`, but more obviously correct async/await style implementations.

### CODE REVIEW

**Comment by Ralith** [comment]
Thanks to @est31 for noticing that something was wrong!

**Comment by est31** [comment]
Thanks @Ralith for finding & fixing the bug!

**Comment by djc** [comment]
Is this worth another maintenance release?

**Comment by Ralith** [comment]
I think that's a good idea, yeah. Sizable footgun.

**Comment by est31** [comment]
@djc indeed I'd love a release with this patch and dd72e10499b78683ac8197bc6085bd72019d635a inside. Because I'm hitting the bug in this PR and I have to workaround missing Eq impls by using if the let trick (but I need != so it's a bit suboptimal to have an empty if let clause followed by else with content).

**Comment by Ralith** [comment]
Folded dd72e10 into #563, we should be able to get that out soon.

**Pull request merged**
