### PR TITLE
QPACK decoder stream

### PR DESCRIPTION
**Pull request by evolix1**
# QPACK encoding

Pull Request: #4 

Current status in functionality:
- [X] Dynamic and Static tables
- [X] Field indexing
- [X] Primitive decoder
- [x] Primitive encoder
- [X] Huffman string decoding
- [x] Huffman string encoding
- [X] Decoder stream
- [ ] Encoder stream
- [ ] Encoding strategies
- [ ] Request and Push stream decoding

Status in development:
- [X] Types are testing separately
- [ ] Testing scenarios that integrate the full pipeline (ex: Frame → Encoder → Decoder → Table)
- [ ] Benchmarks around decoding
- [ ] Benchmarks around encoding

Notable points:
- There are still confusing / misleading points in the draft. Maybe I will have to rework some of the decoding part later.
- I couldn't use `Codec` trait because `Decoder` needs to persists between calls (notable the state of the dynamic table). Instead, you can use `Decoder::feed_stream` as an entry point.

### CODE REVIEW

**Comment by djc** [comment]
This is looking great, I hope you stick with it! I've made some important improvements to packet handling at the transport level that should allow me to go into HTTP again soon, so by then I'll be able to pick up your work and build on it.

**Comment by evolix1** [comment]
Great ! Let me know when you think you'll be read to integrate it.

I've just added huffman string decoding.
At first, it doesn't seem so hard, but testing it is hard. I struggled for 2 days just on testing.
Anyway, it works.

**Comment by evolix1** [comment]
Hi, I got trouble find time and energy to work on Quinn despite motivation being high.
But still, now encoding of primitives (including huffman code) is ready. 
Next step is Encoder stream.

I see you continuously move forwards, I'll do my best to continue on to have Qpack fully done.
Regards.

**Comment by djc** [comment]
Hey, please make sure you don't feel guilty! Only work on it if it's fun for you. I'm already very grateful for all the work you put in. Note that I'm managing to write code for Quinn in large part because I don't have a job right now, so you cannot compare your output to mine and feel bad about yourself...

**Comment by evolix1** [comment]
Hi, I'm fine and back :-)

I managed to find some few days this summer to continue enjoying work on Quinn.
I'm first doing an upgrade of existing code base with new version of QPack draft, version 01.
Later on, I'll start the encoding part.

Anyway, I'm determined to find a healthy way to work on Quinn later alongside work and personal time. It won't be as fast as I would like to, but I hope it will be steady.

You also don't have to worry, I don't feel guilty of anything ;-).

See you.

**Comment by djc** [comment]
Great news! Sorry I haven't gotten any closer to integrating your work...

**Comment by stammw** [comment]
Closing, continued in #136

**Pull request closed without merging**
