### PR TITLE
Interop throughput

### PR DESCRIPTION
**Pull request by stammw**
Introducing a `HTTP/2` endpoint in interop tests to compare throughput with current implementation pair. Feat. `hyper`.

### CODE REVIEW

**Comment by djc** [comment]
Good stuff!

**Comment by stammw** [comment]
The kind of low throughput is gone with last commit's tweaks ! I even get between -30% and -50% compared to h2 :)

**Comment by Ralith** [comment]
Awesome stuff! Should we be adjusting our defaults?

**Comment by djc** [comment]
At least for H3 I think it makes sense to adjust the defaults. Not as sure about base QUIC.

**Comment by Ralith** [comment]
I think the defaults that empirically perform well for H3 in practice are a much better place to start users off than the numbers that I invented on the spot, although we should try to still remain close to the recommendations of the recovery draft where applicable.

**Pull request merged**
