### PR TITLE
Also allow using ECDSA keys in the example

### PR DESCRIPTION
**Pull request by est31**
ECDSA keys are PKCS#8 formatted and need
the PKCS#8 specific function.

### CODE REVIEW

**Comment by briansmith** [comment]
> ECDSA keys are PKCS#8 formatted and need
> the PKCS#8 specific function.

I've not been tracking this, but I hope that you support the PKCS#8 form of RSA keys too, wherever you would also accept some other form.

**Comment by Ralith** [comment]
It looks like this code just reads all PEM keys supplied, be they PKCS#1 or PKCS#8, which should be fine.

**Comment by est31** [comment]
@briansmith I haven't tried it but I believe that this PR will also add PKCS#8 support for RSA keys.

The main reason why I'm doing this PR is to make keys generated by [rcgen](https://github.com/est31/rcgen) work, which right now can only generate ECDSA keys (RSA keys are blocked on RSA keygen support in ring :p). That's why the title and commit msg talk about ECDSA.

Also, the `rsa_private_keys` function is named a bit badly, it should rather be named `pkcs1_private_keys` or something. But that's a problem of rustls :).

**Comment by Ralith** [comment]
Integrated into #168.

**Pull request closed without merging**
