### PR TITLE
fix iOS setsockopt invalid params

### PR DESCRIPTION
**Pull request by SSebo**
fix  https://github.com/djc/quinn/issues/848

### CODE REVIEW

**Review by djc — APPROVED** [review]
Thanks!

**Comment by SSebo** [comment]
@djc Thank you for creating `quinn`!

**Comment by djc** [comment]
@SSebo so are you using Quinn for TiKV/TiDB or something else? Just out of curiosity!

**Comment by SSebo** [comment]
> @SSebo so are you using Quinn for TiKV/TiDB or something else? Just out of curiosity!

Oh, I use it for an instant messaging system with thousands of iOS and Android devices.

**Comment by djc** [comment]
Oh, sounds cool! Is the instant messaging system public, or something proprietary?

It seems like it's there just fine: https://github.com/quinn-rs/quinn/blob/main/quinn/src/platform/unix.rs#L42.

**Comment by SSebo** [comment]
Right now the whole system is not public. We will open source the connection management sub system which is powered by quinn by when we think it is stable.

**Pull request merged**
