### PR TITLE
Merged imports with rustfmt

### PR DESCRIPTION
**Pull request by TimonPost**
- all imports merged  with rustfmt

I very much like imports and think it makes it more readable. If you think otherwise, we can forget about this PR and I close it.

### CODE REVIEW

**Comment by djc** [comment]
The decreased vertical density makes this not an improvement in my opinion even though the prefix separation is slightly more emphasized. @Ralith what do you think?

**Comment by Ralith** [comment]
I don't have a strong opinion either way, though in a vacuum I'm inclined to defer to rustfmt's defaults.

**Comment by djc** [comment]
I think rustfmt is unopinionated on this topic, it just deals with formatting (although it sorts them) but doesn't do adjustments like these either way AFAICT.

**Comment by Ralith** [comment]
Good point. In that case I'm indifferent; feel free to defer to your taste, @djc.

**Comment by djc** [comment]
Okay, let's skip it. Still happy to have that formatting commit, though!

**Comment by TimonPost** [comment]
So what is it going to be? Merge or close?

**Comment by djc** [comment]
@stammw so I guess you are in favor, how attached to it are you?

**Comment by TimonPost** [comment]
Haha, what do you mean that I am attached to it? I ran rustfmt with merge imports on it was 5 minutes of work, so if you don't see the added value, just close this PR. 

However, I think it makes the reading of the imports way more cleaner because there is less repetition when imorting types from the same module paths. I personally like to this with my libraries.

**Comment by stammw** [comment]
I feel we should choose one way of writing imports and stick to it for consistency. I like the nested syntax because it exposes modules structure and contains less useless repetitions. In my opinion having several lines with the same prefix looks a bit ceremonial.

I was planning to apply merged imports syntax in a future readability + documentation pass.

I'm indeed in favor of this PR.

**Comment by djc** [comment]
Alright, let's merge it then. @TimonPost can you rebase it?

**Comment by TimonPost** [comment]
Rebased

**Pull request merged**
