### PR TITLE
Improvements to Endpoint::accept

### LINKED ISSUE #627: Use a token to ensure that `Endpoint::accept()` is not called too many times
Currently, it is easy to call `Endpoint::accept()` too many times, which leads to problems.  Ideally, this would be prevented at compile time.

### PR DESCRIPTION
**Pull request by Ralith**
Fixes #627. Seeking feedback in particular on the final commit; I'm not sure how I feel about complicating the interface to further defend against downstream bugs which the second commit is able to trivialize for substantially less effort.

### CODE REVIEW

**Comment by djc** [comment]
Yeah, this solution feels like it's too indirect. Why don't we decrement `incoming_handshakes` as soon as we yield the corresponding `DatagramEvent` from `Endpoint::handle()`?

**Comment by djc** [comment]
As in, I think the threat model that we've modeled here includes the application (potentially through `quinn`) not handling `NewConnection` events fast enough, when actually we're supposed to be defending against peers initiating too many connections. If we only try to handle the latter, this becomes much more straightforward.

**Comment by DemiMarie-parity** [comment]
@djc `libp2p-quic` actually relies on `accept` for correctness, so that it can put backpressure on incoming connections.  Any `NewConnection` event needs to be either queued or handled immediately, so that `ConnectionEvent`s for other connections can be handled.  In `libp2p-quic`, `Endpoint::accept` is not called until the application has accepted the connection.

Personally, I believe that the complexity of `AcceptToken` is worth it.  Calling `Endpoint::accept` too many times is likely to cause a remotely-triggerable DoS due to memory consumption.

**Comment by Ralith** [comment]
> Why don't we decrement incoming_handshakes as soon as we yield the corresponding DatagramEvent from Endpoint::handle()?

This would make it impossible to exert backpressure on incoming connections, which is an explicit requirement.

> As in, I think the threat model that we've modeled here includes the application (potentially through quinn) not handling NewConnection events fast enough, when actually we're supposed to be defending against peers initiating too many connections.

This isn't a threat model so much as a feature. A server that only has capacity for a certain number of connections can only gracefully express that through use of `Endpoint::accept`, as @DemiMarie-parity describes.

> Calling Endpoint::accept too many times is likely to cause a remotely-triggerable DoS due to memory consumption.

In current master, excess accept calls will (in a release build) cause `incoming_handshakes` to underflow, producing a value which will certainly exceed the `accept_buffer` size of any reasonable configuration, therefore preventing any further connections from being accepted. That's also a DoS, though.

However, the second commit defends against this hazard with much less API impact than the third commit, simply by never allowing the value to underflow. An application which calls `accept` excessively would then simply end up accepting an at worst proportionally larger number of connections.

**Comment by djc** [comment]
As another alternative solution, should we disband `DatagramEvent` such that `NewConnection` and `ConnectionEvent`s are retrieved from `Endpoint`s separately?

**Comment by Ralith** [comment]
I don't think that would work well, because the connection needs to be driven immediately. Failing to call `fn accept(&mut self) -> Option<NewConnection>` continuously would lead to clients timing out rather than being gracefully rejected as in the current scheme.

I went ahead and stripped off the contentious commit; let's merge the obviously reasonable stuff.

**Pull request merged**
